[tool.black]
target-version = ["py310"]
line-length = 79

[tool.isort]
profile = "black"

[tool.ruff]
select = ["ALL"]
ignore = ["D", "FA", "T20", "INP", "PD"]
unfixable = ["ERA001"]

[tool.mypy]
python_version = "3.10"
show_error_context = true
disallow_untyped_defs = true
ignore_missing_imports = true
